# -*- coding: utf-8 -*-
"""rrachynska_praca_domowa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8GzQQGHJEFbZygQGcf7IsDraM4qqpNS

Zadanie 7 – Zliczanie wystąpień
"""

predykcje = ['spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam']

spam = predykcje.count('spam')
ham = predykcje.count('ham')

print(f"spam: {spam}, ham: {ham}")

""" Zadanie 9 – Confusion matrix i metryki"""

cm = [[80, 10],[5, 45]]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
print("Accuracy:", round(accuracy * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")
print("Recall:", round(recall * 100, 2), "%")

"""Zadanie 14 – Ekstrakcja metadanych z nazwy pliku"""

sciezka = "/data/processed/2024/experiment_42_v3.csv"
elementy = sciezka.split('/')
nazwa_pliku = elementy[-1]
rok = elementy[-2]
katalog = "/".join(elementy[:-1])
czesci_pliku = nazwa_pliku.split('.')
nazwa_bez_rozszerzenia = czesci_pliku[0]
rozszerzenie = "." + czesci_pliku[1]
print(f"{'Nazwa pliku:':30} {nazwa_pliku}")
print(f"{'Katalog:':30} {katalog}")
print(f"{'Nazwa bez rozszerzenia:':30} {nazwa_bez_rozszerzenia}")
print(f"{'Rozszerzenie:':30} {rozszerzenie}")
print(f"{'Rok:':30} {rok}")